#+title: Alex Harter Resume
#+author: Alex Harter
#+date: 2024-01-30
* ALEX HARTER
| Houston, TX              |                  | (940) 597-4771                 |
| https://alex.harter.tech | alex@harter.tech | linkedin.com/in/alexhartertech |
** SUMMARY
Dedicated and versatile technology professional with experience in software, music, and education.  Proven ability to quickly learn and apply a variety of technical skills combined with competent oral and written communication and project management skills both as a leader and part of a team.  Passion for problem-solving to discover and beautifully present data insights to drive teams and organizations in exciting and effective directions.
** EXPERIENCE
*** Church Music Consultant
/November 2021 - Present/
+ *Project Management* - Conceive ideas for projects; prioritize those that would be most constructive; delegate tasks to other choir members; and plan and lead monthly rehearsals.
+ *Software* - Utilize publishing, notation, and audio software to create and transmit sheet music, liturgical booklets, and recordings, such as Sunday Matins service booklet used every week.
+ *Performance & Leadership* - Lead choir by singing, conducting, and giving directions in order to make the services more orderly and encourage the congregation to participate.
+ *Mentoring & Collaboration* - Suggest operational improvements and recommend resources to other choir directors.  Collaborate with experts in the field, such as adapting Latin chants into Spanish using GABC.
+ *Education & Teaching* - Educate myself and choir members about musical, linguistic, and historical aspects of Ukrainian and Latin church singing through primary source documents, academic papers, lectures, and communicating with experts.  Learned Cyrillic alphabet as well as Gregorian and Kyivan notation.

*** Data Automation Consultant
/July 2022 - February 2023/
/Encapture | Dallas, TX/
+ *Data Extraction* - Extracted customer-requested information using internal software and Regular Expressions from received documents sorted by machine learning then validated and translated that data according to customer specifications.
+ *Configuration of Pipeline* - Configured internal software within Amazon Web Services to receive and sort customer documents and apply appropriate automation templates at multiple stages.
+ *Presentation* - Demoed in-progress extractions to clients to present progress, ask questions, and teach how to interface with the products.  Clearly presented internal software issues to the Product team with ideas for improvement across all clients.
+ *Documentation* - Edited and Contributed to documentation on Classification software for client use.
+ *Team-Building* - Started a book club with co-workers to improve professional and personal skills.

*** Choir Teacher / Special Education Paraprofessional
/September 2019 - November 2021/
/Responsive Education Solutions | Founders Classical Academy of Corinth/

** EDUCATION
*** Post-Graduate Program in Data Science & Business Analytics (in progress)
+ University of Texas at Austin
+ Curriculum includes Python, Business Statistics, Machine Learning, and Data Visualization with Tableau
*** Bachelor of Science in Rehabilitation Studies | Minor in Music
+ Cumulative GPA: 3.74
+ University of North Texas | Denton, TX
+ Graduated /Magna Cum Laude December 2019
+ Coursework included Statistics, Music Theory & Composition, Case Management, and Special Education
*** Texas Educator Certification Examination Program
+ Content certified in Music EC-12 & Special Education EC-12

** SKILLS
+ *Technical Skills:* Python, Java, SQL, C, Excel, Word, Regular Expressions, Linux, Git, Emacs, Publishing Software, Audio Software, Typing
+ *Soft Skills:* Agile, Gettings Things Done, Project Management, Teamwork, Communication, Attention to Detail, Problem Solving, Organization, Teaching
